apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: frontend
    name: frontend-service
    namespace: dev-workspace
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: frontend
    type: ClusterIP
kind: List
